#!/usr/bin/env python3
# NSN (Network Security Navigator)
# Copyright (c) NSN Contributors
# Licensed under MIT License
#
# File: freeze.py
# Description: Embeds the NSN standard library into C source for distribution.

import os
import sys

def freeze_to_c(lib_dir, output_file):
    print(f"Freezing NSN records from {lib_dir}...")
    
    with open(output_file, 'w', encoding='utf-8') as out:
        out.write("/* Automatically generated by Tools/freeze/freeze.py */\n")
        out.write("#include \"nsn.h\"\n\n")
        
        module_names = []
        
        for root, dirs, files in os.walk(lib_dir):
            for file in files:
                if file.endswith(".nsn"):
                    rel_path = os.path.relpath(os.path.join(root, file), lib_dir)
                    # Convert 'protocol/icmp.nsn' to 'protocol_icmp'
                    mod_name = rel_path.replace(os.sep, '_').replace('.nsn', '')
                    module_names.append((rel_path.replace(os.sep, '.').replace('.nsn', ''), mod_name))
                    
                    with open(os.path.join(root, file), 'rb') as f:
                        data = f.read()
                    
                    out.write(f"static const unsigned char _nsn_frozen_data_{mod_name}[] = {{\n")
                    for i, byte in enumerate(data):
                        out.write(f"0x{byte:02x},")
                        if (i + 1) % 12 == 0: out.write("\n    ")
                    out.write("\n};\n\n")

        # Table of frozen modules
        out.write("const struct _nsn_frozen _nsn_frozen_modules[] = {\n")
        for full_name, mod_name in module_names:
            out.write(f"    {{\"{full_name}\", _nsn_frozen_data_{mod_name}, {len(data)}}},\n")
        out.write("    {NULL, NULL, 0}\n")
        out.write("};\n")

    print(f"Successfully generated {output_file}")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: freeze.py <lib_dir> <output.c>")
    else:
        freeze_to_c(sys.argv[1], sys.argv[2])
