name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libpcap-dev \
          libssl-dev \
          libssh-dev \
          python3 \
          python3-pip
          
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Run Unit Tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: nsn-linux
        path: build/nsn

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        brew install cmake libpcap openssl libssh
        
    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release \
          -DOPENSSL_ROOT_DIR=$(brew --prefix openssl)
      
    - name: Build
      run: cmake --build build --config Release

    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: nsn-macos
        path: build/nsn

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: cmake --build build --config Release

    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: nsn-windows
        path: build/Release/nsn.exe
